channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.11.8
  - certifi=2020.11.8
  - cudatoolkit=10.1.243
  - freetype=2.10.4
  - igl=2.2.1
  - intel-openmp=2020.2
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - pillow=8.0.1
  - pip=20.2.4
  - python=3.8.5
  - python_abi=3.8
  - pytorch=1.6.0
  - readline=8.0
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.7.0
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - ase==3.20.1
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - future==0.18.2
    - googledrivedownloader==0.4
    - h5py==3.1.0
    - idna==2.10
    - imageio==2.9.0
    - isodate==0.6.0
    - jinja2==2.11.2
    - joblib==0.17.0
    - kiwisolver==1.3.1
    - llvmlite==0.34.0
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - networkx==2.5
    - numba==0.51.2
    - openmesh==1.1.4.post18
    - pandas==1.1.4
    - plyfile==0.7.2
    - progressbar2==3.53.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-utils==2.4.0
    - pytz==2020.4
    - pywavelets==1.1.1
    - rdflib==5.0.0
    - requests==2.25.0
    - robust-laplacian==0.1.0
    - scikit-image==0.17.2
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - threadpoolctl==2.1.0
    - tifffile==2020.11.18
    - torch-cluster==1.5.8
    - torch-geometric==1.4.3
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - tqdm==4.53.0
    - urllib3==1.26.2
